
apiVersion: v1
kind: Namespace
metadata:
  name: contrail
---
apiVersion: v1
kind: ServiceAccount
metadata:
 name: contrail-control-serviceaccount
 namespace: contrail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrail-control-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contrail-control-rolebinding
subjects:
- kind: ServiceAccount
  name: contrail-control-serviceaccount
  namespace: contrail
roleRef:
  kind: ClusterRole
  name: contrail-control-role
  apiGroup: rbac.authorization.k8s.io
---
#Contrail Control
apiVersion: v1
kind: Service
metadata:
  name: contrail-control
  namespace: contrail
spec:
  selector:
    app: contrail-control
  ports:
  - name: xmpp
    protocol: TCP
    port: 5269
    targetPort: 5269
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-control-configmap
  namespace: contrail
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: contrail-control-secret
  namespace: contrail
data:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrail-control
  namespace: contrail
  labels:
    app: contrail-control
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contrail-control
  template:
    metadata:
      labels:
        app: contrail-control
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
      - name: config-volume
        configMap:
          name: contrail-control-configmap
      - name: secret-volume
        secret:
          secretName: contrail-control-secret
      serviceAccountName: contrail-control-serviceaccount
      initContainers:
      - name: contrail-init
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
        imagePullPolicy: Always
        image: michaelhenkel/contrail-init:distroless
        #command: ["sh","-c","while true; do sleep 10;done"]
        command: ["/contrail-init"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
      containers:
      - name: contrail-control
        image: michaelhenkel/contrail-control:distroless
        imagePullPolicy: Always
        #command: ["sh","-c","cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt >> /etc/ssl/certs/ca-certificates.crt && /contrail-control --conf_file /etc/contrail/contrail-control-${HOSTNAME}.conf"]
        command: ["sh","-c","while true; do sleep 10;done"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: config-volume
          mountPath: /etc/contrail
        - name: secret-volume
          mountPath: "/etc/contrailkeys"
---
#Contrail Vrouter Master
apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-vrouter-master-configmap
  namespace: contrail
data:
---
apiVersion: v1
kind: Secret
metadata:
  name: contrail-vrouter-master-secret
  namespace: contrail
data:
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: contrail-vrouter-master
  namespace: contrail
  labels:
    app: contrail-vrouter
spec:
  selector:
    matchLabels:
      name: contrail-vrouter-master
      app: contrail-vrouter
  template:
    metadata:
      labels:
        name: contrail-vrouter-master
        app: contrail-vrouter
    spec:
      serviceAccountName: contrail-control-serviceaccount
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      initContainers:
      - name: contrail-init
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
        imagePullPolicy: Always
        image: michaelhenkel/contrail-init:distroless
        command: ["sh","-c","while true; do sleep 10;done"]
        #command: ["/contrail-init"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: GATEWAY
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['gateway']
        - name: MASK
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['mask']
      - name: contrail-vrouter-kernel
        volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
        imagePullPolicy: Always
        image: michaelhenkel/contrail-vrouter:distroless
        command: ["sh","-c","/init_kmod.sh create"]
        #command: ["sh","-c","echo hello"]
        #command: ["sh","-c","while true; do sleep 10;done"]
        securityContext:
          capabilities:
            add: ["CAP_SYS_MODULE","NET_ADMIN"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: APP
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app']
        - name: INTERFACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['interface']
        - name: VHOSTEXISTS
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['vhostExists']
        - name: MAC
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['mac']
        - name: CONTROLNODENAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['controlNodeName']
      containers:
      - name: contrail-vrouter-agent
        image: michaelhenkel/contrail-agent:distroless
        #command: ["sh","-c","cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt >> /etc/ssl/certs/ca-certificates.crt && /contrail-vrouter-agent --conf_file /etc/contrail/contrail-vrouter-${HOSTNAME}.conf"]
        command: ["sh","-c","while true; do sleep 10;done"]
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: PODIP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/contrail
        - name: secret-volume
          mountPath: "/etc/contrailkeys"
      volumes:
      - name: podinfo
        downwardAPI:
          items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
      - name: config-volume
        configMap:
          name: contrail-vrouter-master-configmap
      - name: secret-volume
        secret:
          secretName: contrail-vrouter-master-secret